### ISSUE TITLE
Write unit tests

### ISSUE THREAD

**Issue by Esemesek** [react-native-community/art#7]
There is quite a bit of logic in [`lib`](https://github.com/react-native-community/art/tree/master/lib) directory, but there are no unit tests to verify if nothing is broken. Lack of unit tests makes it harder to refactor/change existing code.

### TODO
- [ ] - Implement unit tests for `lib/helpers` - *This is the most important one because most of logic exists here*
- [ ] - Implement unit tests for `lib/LinearGradient`
- [ ] - Implement unit tests for `lib/RadialGradient`

**Comment by yeswanth** [comment]
I would like to start on `lib/helpers` with tests to check simple functions (to begin with). Will be using `jest` for testing. I am maintaining the tests to be written in this [spreadsheet](https://docs.google.com/spreadsheets/d/1U07zjIKBw-_OUHg4CfdoodgVpwh0pTT3v3XA3xfCwh8/edit?usp=sharing).
